## Estadística Aplicada
Sesión 2 - 10 Agosto

Cinthia Zaydé García Belmonte 2076329


Una lista en Python es una colección de objetos que pueden ser de distinto tipo

In [14]:
alumno = [ 'Zaydé', 'García', 22]
alumno
type(alumno)

list

In [17]:
estadistica_G44 = ['Andrea', 'Ana', 'Carlos', 'Hugo']

In [18]:
#Seleccionar Ana de la lista
estadistica_G44[1]

'Ana'

In [19]:
#Elegir a Carlos
estadistica_G44[2]

'Carlos'

In [20]:
estadistica_G44[0:2]

['Andrea', 'Ana']

In [21]:
estadistica_G44.append('Raúl')

In [22]:
estadistica_G44

['Andrea', 'Ana', 'Carlos', 'Hugo', 'Raúl']

In [51]:
estadistica_G44.remove('Hugo')

In [52]:
estadistica_G44

['Andrea', 'Ana', 'Carlos', 'Raúl']

In [2]:
yo_enFCFM = ['Zaydé', 'LA', 89]

In [3]:
mi_promedio = yo_enFCFM[2]
mi_carrera = yo_enFCFM[1]

In [4]:
print('promedio:', mi_promedio, 'mi carrera:', mi_carrera)

promedio: 89 mi carrera: LA


## Librerias/paquetes/modulos
Una libreria en python es un conunto de codigos que le indican a python como hacer determinadas acciones

para usar una libreria:
1. primero se instala
2. se le indica a python que la utilice

In [5]:
pip install yfinance

                                              0.0/63.2 kB ? eta -:--:--
     -------------------------                41.0/63.2 kB 1.9 MB/s eta 0:00:01
     -------------------------------------- 63.2/63.2 kB 678.6 kB/s eta 0:00:00
                                              0.0/10.7 MB ? eta -:--:--
                                              0.1/10.7 MB 2.6 MB/s eta 0:00:05
     -                                        0.3/10.7 MB 3.4 MB/s eta 0:00:04
     -                                        0.5/10.7 MB 3.9 MB/s eta 0:00:03
     ---                                      0.8/10.7 MB 4.8 MB/s eta 0:00:03
     ----                                     1.1/10.7 MB 4.7 MB/s eta 0:00:03
     -----                                    1.5/10.7 MB 5.2 MB/s eta 0:00:02
     -------                                  2.1/10.7 MB 6.2 MB/s eta 0:00:02
     ---------                                2.6/10.7 MB 7.0 MB/s eta 0:00:02
     ----------                               2.9/10.7 MB 6.9 MB


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\fcfm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [6]:
import yfinance as yf #yf es un apodo

In [7]:
#yfinance.download('US.MX','') #TIPO DE CAMBIO
yf.download

[*********************100%***********************]  1 of 1 completed


1 Failed download:
['US.MX']: ValueError("time data '' does not match format '%Y-%m-%d'")


Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

## Numpy (numerical python)
Libreria que le sirve a Python para manejar numeros.
La estructura basica de numpy son los arreglos. Una colección de objetos del mismo tipo (numerico)

Vamos a suponer que tenemos la venta de aguas de la cafeteria de FCFM de la semana: Lunes 23, Martes 35, Miercoles 40, Jueves 28, Viernes 20

In [8]:
ventas = [23,35,40,28,20]

In [9]:
import numpy as np

In [10]:
# convertir la lista en un arreglo
ventas = np.array(ventas)

In [11]:
ventas

array([23, 35, 40, 28, 20])

In [13]:
#suma
np.sum(ventas)

146

In [26]:
#multiplicacion
np.product(ventas)

18032000

In [30]:
#maximo
np.max(ventas)

40

In [31]:
#minimo
np.min(ventas)

20

In [24]:
#media/promedio
np.mean(ventas)

29.2

In [27]:
#mediana
np.median(ventas)

28.0

In [28]:
#varianza (poblacional)
np.var(ventas)

54.96

In [32]:
#desviacion estandar (poblacional)
np.std(ventas,ddof=0)

7.413501197140255

In [33]:
#varianza muestral
np.var(ventas, ddof=1)

68.7

In [34]:
#desiacion muestral
np.std(ventas, ddof=1)

8.28854631404084

In [36]:
#vector
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
#vector
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,100,15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [39]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [43]:
np.random.seed(12)
## Distribucion uniforme
aleatorios = np.random.randint(0,25,10)
aleatorios

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])

In [44]:
aleatorios = np.sort(aleatorios)

In [47]:
#contar los numeros aleatorios
len(aleatorios)

10

In [46]:
# función
np.random.seed(19)
aleatorios2 = np.random.randint(0,25,9)


array([ 2,  3,  3,  6, 11, 12, 16, 17, 17, 22])

In [48]:
#
numeros = [2.45,9.89,12.4567]


1. arreglos
2. media
3. redondear a dos decimales

In [49]:
#funcion
round(np.mean(np.array(numeros)), 2)


8.27

In [50]:
#metodo
np.array(numeros).mean().round(2)

8.27